"""Disposable Chromium rasterizer for the trusted poster SVG seam.

The worker has no target URL and no network-dependent inputs.  It reads one
SVG generated by ``render-poster-svg.mjs``, paints it in a blank page, and
atomically writes PNG bytes plus a nonce-scoped, metadata-only result envelope.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

from .svg_rasterizer import rasterize_svg_frames


RESULT_NONCE_ENV = "DOM_X_RAY_WORKER_RESULT_NONCE"
RENDER_ROOT_ENV = "DOM_X_RAY_POSTER_RENDER_ROOT"
RENDER_VERSION = "poster-renderer-v0.1.0"
POSTER_SIZE = 1080
MAX_PNG_BYTES = 5_000_000
MAX_BUNDLE_BYTES = 8 * 1024 * 1024
MAX_SVG_BYTES = 2_000_000


def _args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--bundle", required=True)
    parser.add_argument("--node", required=True)
    parser.add_argument("--svg", required=True)
    parser.add_argument("--png", required=True)
    parser.add_argument("--result", required=True)
    return parser.parse_args()


def _render_root() -> Path:
    value = os.environ.get(RENDER_ROOT_ENV, "")
    root = Path(value)
    if not root.is_absolute() or root.is_symlink() or not root.is_dir():
        raise ValueError("poster render root is invalid")
    return root.resolve(strict=True)


def _private_path(
    argument: str,
    label: str,
    *,
    root: Path,
    must_exist: bool,
) -> Path:
    path = Path(argument)
    if not path.is_absolute() or path.parent.resolve(strict=True) != root:
        raise ValueError(f"{label} path escaped the poster render root")
    if must_exist:
        if path.is_symlink() or not path.is_file():
            raise ValueError(f"{label} input is not a regular file")
    elif path.exists():
        raise ValueError(f"{label} output already exists")
    return path.resolve(strict=False)


def _trusted_node(argument: str) -> Path:
    path = Path(argument)
    if not path.is_absolute() or path.is_symlink() or not path.is_file():
        raise ValueError("Node runtime path is invalid")
    return path.resolve(strict=True)


def _write_atomic(path: Path, payload: bytes) -> None:
    with tempfile.NamedTemporaryFile(
        mode="wb", dir=path.parent, prefix=f".{path.name}.", delete=False
    ) as temporary:
        temporary_path = Path(temporary.name)
        temporary.write(payload)
        temporary.flush()
        os.fsync(temporary.fileno())
    try:
        os.replace(temporary_path, path)
    except BaseException:
        temporary_path.unlink(missing_ok=True)
        raise


def main() -> int:
    arguments = _args()
    root = _render_root()
    bundle_path = _private_path(
        arguments.bundle,
        "bundle",
        root=root,
        must_exist=True,
    )
    svg_path = _private_path(arguments.svg, "SVG", root=root, must_exist=False)
    png_path = _private_path(arguments.png, "PNG", root=root, must_exist=False)
    result_path = _private_path(arguments.result, "result", root=root, must_exist=False)
    node_path = _trusted_node(arguments.node)
    if bundle_path.stat().st_size <= 0 or bundle_path.stat().st_size > MAX_BUNDLE_BYTES:
        raise ValueError("poster bundle is outside the input byte envelope")
    nonce = os.environ.get(RESULT_NONCE_ENV)
    if not nonce or len(nonce) > 128:
        raise ValueError("missing worker result nonce")
    helper = Path(__file__).resolve().parents[1] / "viewer" / "scripts" / "render-poster-svg.mjs"
    generated = subprocess.run(
        [
            str(node_path),
            "--no-warnings",
            "--experimental-strip-types",
            str(helper),
            str(bundle_path),
            str(svg_path),
        ],
        cwd=Path(__file__).resolve().parents[1],
        stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        shell=False,
        timeout=3.0,
        check=False,
    )
    if (
        generated.returncode != 0
        or svg_path.is_symlink()
        or not svg_path.is_file()
        or not 0 < svg_path.stat().st_size <= MAX_SVG_BYTES
    ):
        raise RuntimeError("SVG generation failed")
    svg = svg_path.read_text(encoding="utf-8")
    png = rasterize_svg_frames([svg], size=POSTER_SIZE)[0]
    if len(png) == 0 or len(png) > MAX_PNG_BYTES:
        raise ValueError("PNG is outside the approved byte envelope")
    _write_atomic(png_path, png)
    envelope = {
        "supervisorNonce": nonce,
        "result": {
            "status": "ok",
            "version": RENDER_VERSION,
            "width": POSTER_SIZE,
            "height": POSTER_SIZE,
            "byteLength": len(png),
            "artifactPath": str(png_path),
        },
    }
    _write_atomic(result_path, (json.dumps(envelope, separators=(",", ":")) + "\n").encode("utf-8"))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception:
        # Supervisor receives only the exit code and bounded artifact state.
        raise SystemExit(1)
